### ISSUE TITLE
Action failed with error: Service tier not recognizable in service

### ISSUE THREAD

**Issue by brijshah27** [Azure/spring-apps-deploy#34]
Using the sample from the readme with following action

```
        name: deploy to production with artifact
        uses: Azure/spring-apps-deploy@v1
        with:
          azure-subscription: 
```

Getting this error: Error: Action failed with error: Service tier not recognizable in service `appname` app `serviceName`.
Using Azure spring apps on `Standard consumption & dedicated (preview)`
